### ISSUE TITLE
Some (especially zip) files are incorrect - no information in them

### ISSUE THREAD

**Issue by eulers-secret** [lxaw/ComprehensiveFoodDatabase#5]
Hello!

The zip files that have been added to this repository contain no data, only some ASCII text:
https://github.com/lxaw/ComprehensiveFoodDatabase/blob/master/sql/db.zip
https://github.com/lxaw/ComprehensiveFoodDatabase/blob/master/imgs.zip

The table_design document has the same problem:
https://github.com/lxaw/ComprehensiveFoodDatabase/blob/master/sql/table_design/table_design.pdf

Both contain text which looks like this (from img.zip):
```
version https://git-lfs.github.com/spec/v1
oid sha256:d42fb1f4e573dfdc4f4027e258426e88528462008b166d2fb2528df4ceeeb74a
size 1558049162
```

Would you mind re-pushing the full zip files for this database? Seems really useful, thanks for all the effort so far! 

EDIT: I see the size of img.zip is itself ~1.5GB, so you'll have to use LFS to upload these files: https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github  

You may even have to host the files elsewhere and provide a link.

**Comment by eulers-secret** [comment]
I'm dumb, this is git lfs. thanks.

**Comment by lxaw** [comment]
@eulers-secret No worries! Random but do you happen to know a better way to store many files? Git LFS has a cap that is quite annoying.
