### ISSUE TITLE
missing download link

### ISSUE THREAD

**Issue by jrhizor** [lxaw/ComprehensiveFoodDatabase#7]
In the main readme: 

> The link to zip files of the database files and images can be found [here](https://github.com/lxaw/ComprehensiveFoodDatabase).

The link just goes to the repo. I did find a download on https://blog.jpoles1.com/archives/277, but I assume there is supposed to be an actual link in the readme?

**Comment by lxaw** [comment]
Thank you for noticing; please try this updated link: https://mega.nz/folder/0elAXR6L#QuC3C95Od8wn_j0jcn-d4A (should take you to a Mega repository).

**Comment by lxaw** [comment]
Unless issues are present with the Mega link, I am closing this issue.
